Transmission BitTorrent client completions
carapace-sh/carapace-bin pull request #2319
Opened 2024-03-31 21:24 UTC by aftix

This PR adds completions for the transmission BitTorrent client. The included commands are:

- `transmission-cli`
- `transmission-edit`
- `transmission-show`
- `transmission-create`
- `transmission-daemon`
- `transmission-remote`

Some of these commands have tab completions for IP addresses, so I experimented with adding an action for IPv6 to match the current IPv4 action, but decided that each segment of an IPv6 address has too many options and the completions just fill the terminal.

2024-04-01 10:07 UTC, rsteube requested changes
`ActionIds` is the only blocking issue.

2024-04-01 10:07 UTC, rsteube commented on completers/transmission-cli_completer/cmd/root.go
> +	carapace.Gen(rootCmd).PositionalCompletion(carapace.ActionFiles(".torrent", ".magnent"))
This is probably `.magnet`?

2024-04-01 10:07 UTC, rsteube commented on completers/transmission-remote_completer/cmd/root.go
> +		"add":                 carapace.ActionFiles(".torrent", ".magnent"),
`.magnet`?

2024-04-01 10:07 UTC, rsteube commented on completers/transmission-show_completer/cmd/root.go
> +	rootCmd.Flags().BoolP("magnent", "m", false, "Show a magnent link for the specified .torrent file")
`magnet`?

2024-04-01 10:07 UTC, rsteube commented on completers/transmission-create_completer/cmd/root.go
> +		carapace.Batch(carapace.ActionDirectories(), carapace.ActionFiles()).ToA(),
`ActionFiles` already includes directories.

2024-04-01 10:07 UTC, rsteube commented on completers/transmission-edit_completer/cmd/root.go
> +			return carapace.ActionValues()
This isn't doing anything at the moment, is it?

2024-04-01 10:07 UTC, rsteube commented on pkg/actions/tools/transmission/tos.go
> +	).StyleF(style.ForKeyword)
Don't think I've got any of these in keywords at the moment. Is it meant for `default`?
It's mostly for keywords representing a positive/negative/ambiguous state.

2024-04-01 10:07 UTC, rsteube commented on pkg/actions/tools/transmission/path.go
> +	return carapace.ActionDirectories().Chdir("/")
Not sure if I would have went for a shared action on these :thinking: .
I can see the repetition, but it's still a simple case and doesn't provide much value to to other commands.

I'm fine with this solution though.

2024-04-01 10:07 UTC, rsteube commented on pkg/actions/tools/transmission/filter.go
> +func ActionFilter() carapace.Action {
`ActionFilters` - don't think it's consistent at the moment, but I'm trying to have these end in plural where possible.

2024-04-01 10:07 UTC, rsteube commented on pkg/actions/tools/transmission/filter.go
> +	filters := make([]string, len(rawFilters)*2+1)
I did this in the past as well but nowadays i just use `append`.
There's no performance issue at this point and it's a lot more readable.

```go
	args := []string{"-l"}
	for _, f := range rawFilters {
		args = append(args, "-F", f)
	}
```

I'm fine with this solution though.

2024-04-01 10:07 UTC, rsteube commented on pkg/actions/tools/transmission/filter.go
> +					"n:", "torrent name includes the string following :",
Depents on what one wants, but fyi there's [Suffix](https://carapace-sh.github.io/carapace/carapace/action/suffix.html) which hides the `:` from the displayed values during completion.

2024-04-01 10:07 UTC, rsteube commented on completers/transmission-remote_completer/cmd/root.go
> +		"torrent":             transmission.ActionIds(rootCmd),
```go
		"torrent": carapace.ActionCallback(func(c carapace.Context) carapace.Action {
			filters, _ := rootCmd.Flags().GetStringArray("filter")
			return transmission.ActionIds(filters...)
		}),
```

2024-04-01 10:07 UTC, rsteube commented on completers/transmission-remote_completer/cmd/root.go
> +	rootCmd.Flags().StringSliceP("torrent", "t", nil, "Set the current torrent(s) for use by subsequent options")
Not sure how cobra handles `nil` here when accessed with `GetStringArray`.
```go
rootCmd.Flags().StringSliceP("torrent", "t", []string{}, "Set the current torrent(s) for use by subsequent options")
```

2024-04-01 10:07 UTC, rsteube commented on pkg/actions/tools/transmission/filter.go
> +func ActionIds(cmd *cobra.Command) carapace.Action {
Actions in `pkg/actions` are implicitly exposed as [macros](https://carapace-sh.github.io/carapace-bin/spec/macros.html) and signature must match one of:
- [MacroI](https://pkg.go.dev/github.com/carapace-sh/carapace-spec#MacroI)
- [MacroN](https://pkg.go.dev/github.com/carapace-sh/carapace-spec#MacroN)
- [MacroV](https://pkg.go.dev/github.com/carapace-sh/carapace-spec#MacroV)

As they are shared they also must not be coupled to a command. Passing `cobra.Command` is a [valid pattern](https://carapace-sh.github.io/carapace-bin/development/bestPractices/coupledActions.html), but only for local actions (`my_completer/cmd/action/`).

```go
func ActionIds(filters ...string) carapace.Action {
```

2024-04-01 14:02 UTC, aftix commented on completers/transmission-edit_completer/cmd/root.go
> +			return carapace.ActionValues()
It isn't, how do I encode that --replace is followed by two strings separated by a space?

2024-04-02 14:21 UTC, rsteube commented on completers/transmission-edit_completer/cmd/root.go
> +			return carapace.ActionValues()
Ah, it's one of those abominations.

I got basic support for this now in [pflag](https://github.com/carapace-sh/carapace-pflag?tab=readme-ov-file#nargs):
```go
rootCmd.Flag("replace").Nargs = 2
```

2024-04-02 14:38 UTC, aftix commented
Updated the branch to be rebased against master again and pushed a commit addressing all the review comments

2024-04-02 15:00 UTC, merged

2024-04-02 15:00 UTC, rsteube commented
thanks