Updated nix completer with the new flake APIs
carapace-sh/carapace-bin pull request #2350
Opened 2024-04-16 19:19 UTC by aftix

- Created an ActionInstallables for installables from flakes or nixpkgs
- Added `--stdin` flags to commands taking installables
- Added several subcommands under `nix flake`
- Removed old subcommands that have been renamed or removed from the nix program

Due to https://github.com/carapace-sh/carapace-bin/issues/2348#issuecomment-2059487194 tab completion for flake outputs was not implemented. Also, `nix help` follows the somewhat common pattern of putting subcommands as positional arguments such as `nix help flake show` to show help for `nix flake show`. I wasn't aware of a good programatic way to generate those completions.

2024-04-16 20:41 UTC, rsteube commented
Regarding the help command:
```go
carapace.Gen(helpCmd).PositionalAnyCompletion(
    carapace.ActionCommands(rootCmd),
)
```
e.g. https://github.com/carapace-sh/carapace-bin/blob/e95f07dba3c876d947784b5de530fc1597ce5c24/completers/dagger_completer/cmd/help.go#L20

2024-04-16 23:47 UTC, aftix commented
I've added the ActionCommands to `nix help` and rebased against master again

2024-04-17 21:07 UTC, rsteube requested changes

2024-04-17 21:07 UTC, rsteube commented on pkg/actions/tools/nix/develop.go
> +	if err := cmd.Run(); err != nil {
There's `Output` when stderr isn't needed:
`output, err := c.Command("nix", "show-config", "--json").Output()`

2024-04-17 21:07 UTC, rsteube commented on pkg/actions/tools/nix/develop.go
> +	cmd := exec.Command("nix", "show-config", "--json")
Better pass `c carapace.Context`  to the command and use `c.Command`.
Directly accessing `os.Getenv` and `exec.Command` in actions should be avoided.
Context contains the workdir and environment variables which might have changed at some point.
`Context.Command` takes care of setting these in the command and also logs executions.

2024-04-17 21:07 UTC, rsteube commented on pkg/actions/tools/nix/develop.go
> +		return ""
Maybe return `(string, error)` and use `ActionMessage` to give some response if it should ever fail.
Or is there a situation where it is expected to fail?

2024-04-17 21:07 UTC, rsteube commented on pkg/actions/tools/nix/develop.go
> +					return style.White
`style.White` might be problematic on bright themes (I tend to avoid setting white/black). `style.Default` (which is the default and just an empty string) is normally "white" anyway.
So far I've been using `style.Blue` as primary highlight color (not that it matters).
So maybe highlight this one in color and use `style.Default` for the rest.

2024-04-17 21:07 UTC, rsteube commented on pkg/actions/tools/nix/installables.go
> +
Short description for the macro would be nice.

2024-04-17 21:07 UTC, rsteube commented on pkg/actions/tools/nix/templates.go
> +			return carapace.ActionValues()
```go
return carapace.ActionMessage(err.Error())
```

2024-04-17 21:07 UTC, rsteube commented on pkg/actions/tools/nix/develop.go
> +					return carapace.ActionValues()
```go
return carapace.ActionMessage(err.Error())
```

2024-04-17 21:07 UTC, rsteube commented on pkg/actions/tools/nix/develop.go
> +			return carapace.ActionValues()
This is fine, but should never happen. With `ActionMultiPartsN` `c.Parts` won't exceed the length `n-1`.

2024-04-17 21:07 UTC, rsteube commented on completers/nix_completer/cmd/derivationAdd.go
I use `_` to separate subcommands and camelcase as replacement for `-` in names (consistent with variable name).
So `derivation_add.go` and  `derivation_show.go`.

2024-04-17 21:33 UTC, aftix commented
I've made the requested changes, but wasn't exactly sure what kind of error messages would be good on failure

2024-04-17 21:53 UTC, rsteube commented on pkg/actions/tools/nix/installables.go
> +
Ah, sorry :sweat_smile: . The oneliner would have been enough (it's used for completion and the macro site in the docs).

2024-04-17 21:55 UTC, rsteube commented
Just `err.Error()` is fine.

2024-04-17 21:58 UTC, aftix commented
I've updated the ActionMessage calls to use `err.Error()`

2024-04-17 22:03 UTC, rsteube approved these changes

2024-04-17 22:09 UTC, merged

2024-04-17 22:09 UTC, rsteube commented
thanks